# Generated by Django 5.2.13 on 2026-04-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='name',
        ),
    ]
