# Generated by Django 5.2.11 on 2026-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=20)),
                ('pr_items', models.IntegerField()),
                ('pr_sepecification', models.CharField(max_length=30)),
            ],
        ),
    ]
