# Generated by Django 5.2.12 on 2026-03-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobilenumber', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('dob', models.DateField()),
            ],
        ),
    ]
