# Generated by Django 5.2.12 on 2026-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('dept', models.CharField(max_length=20)),
                ('addess', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=20)),
                ('quntity', models.IntegerField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
