# Generated by Django 5.2.13 on 2026-05-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('available', models.CharField(max_length=20)),
            ],
        ),
    ]
