# Generated by Django 5.2.12 on 2026-04-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emp/'),
        ),
    ]
